etcd_name               = ""
etcd_svc_account        = "etcd-cluster@<service_account>.iam.gserviceaccount.com"
external_ip_name        = ""
initialize_params_image = "ubuntu-os-cloud/ubuntu-1804-lts"
initialize_params_size  = 100
initialize_params_type  = "pd-ssd"
internal_ip_name        = ""
labels = {
  env     = "prod"
  for     = "gp"
  service = "etcd-cluster"
}
machine_type = "n1-standard-4"
network      = ""
project      = ""
region       = "asia-east1"
scopes       = ["https://www.googleapis.com/auth/devstorage.read_only", "https://www.googleapis.com/auth/logging.write", "https://www.googleapis.com/auth/monitoring.write", "https://www.googleapis.com/auth/service.management.readonly", "https://www.googleapis.com/auth/servicecontrol", "https://www.googleapis.com/auth/trace.append", "https://www.googleapis.com/auth/compute"]
tags         = ["etcd"]
replica      = 3
zones        = ["asia-east1-a", "asia-east1-b", "asia-east1-c"]
